import { Property, Enclave, AgentProfile, SiteSettings } from '../../../types/real-estate';

// Generated high-fidelity asset paths
export const ASSETS = {
  heroMansion: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1600&q=80',
  siestaBeach: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
  jennaRyan: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=800&q=80',
  lakewoodGolf: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80',
  downtownSkyline: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80',
  longboatBeachfront: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80',
  birdKeyEstate: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
  palmerRanchHome: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80'
};

export const INITIAL_PROPERTIES: Property[] = [
  {
    id: '4128-ocean-blvd',
    slug: '4128-ocean-blvd',
    title: '4128 Ocean Blvd',
    street: '4128 Ocean Blvd',
    city: 'Siesta Key',
    state: 'FL',
    zip: '34242',
    price: 2450000,
    priceFormatted: '$2,450,000',
    beds: 4,
    baths: 5,
    sqft: 4210,
    mlsNumber: 'A4592031',
    status: 'ACTIVE MLS',
    isWaterfront: true,
    hasPool: true,
    isNewConstruction: false,
    featured: true,
    propertyType: 'Single Family',
    imageUrl: ASSETS.siestaBeach,
    yearBuilt: 2021,
    lotSize: '0.45 Acres',
    hoaFee: '$0 / No HOA',
    excerpt: 'Siesta Key, FL 34242 · 4 Beds · 5 Baths · 4,210 Sq Ft',
    description: 'Breathtaking coastal luxury residence situated just steps from the world-famous quartz sands of Siesta Key Beach. Features expansive open concept living, gourmet chef kitchen with Wolf/Sub-Zero appliances, private heated pool and spa, and a rooftop deck with panoramic Gulf sunset views.',
    idxDisclaimer: 'Listing information courtesy of Stellar MLS. Information is deemed reliable but not guaranteed. IDX provided by iHomefinder Inc.'
  },
  {
    id: '7314-whitemarsh-cir',
    slug: '7314-whitemarsh-cir',
    title: '7314 Whitemarsh Cir',
    street: '7314 Whitemarsh Cir',
    city: 'Lakewood Ranch',
    state: 'FL',
    zip: '34202',
    price: 1280000,
    priceFormatted: '$1,280,000',
    beds: 3,
    baths: 3,
    sqft: 2850,
    mlsNumber: 'A4592088',
    status: 'ACTIVE MLS',
    isWaterfront: false,
    hasPool: true,
    isNewConstruction: true,
    featured: true,
    propertyType: 'Single Family',
    imageUrl: ASSETS.lakewoodGolf,
    yearBuilt: 2024,
    lotSize: '0.32 Acres',
    hoaFee: '$280 / Month',
    excerpt: 'Lakewood Ranch, FL 34202 · 3 Beds · 3 Baths · 2,850 Sq Ft',
    description: 'Exquisite custom golf-front estate in premier Lakewood Ranch community. Soaring ceilings, designer finishes, seamless indoor-outdoor lanai with outdoor kitchen, overlooking the 14th fairway. Complete with private saltwater pool and hurricane impact glass throughout.',
    idxDisclaimer: 'Listing information courtesy of Stellar MLS. Information is deemed reliable but not guaranteed. IDX provided by iHomefinder Inc.'
  },
  {
    id: '35-watergate-dr-904',
    slug: '35-watergate-dr-904',
    title: '35 Watergate Dr #904',
    street: '35 Watergate Dr #904',
    city: 'Downtown Sarasota',
    state: 'FL',
    zip: '34236',
    price: 895000,
    priceFormatted: '$895,000',
    beds: 2,
    baths: 2,
    sqft: 1740,
    mlsNumber: 'A4592115',
    status: 'ACTIVE MLS',
    isWaterfront: true,
    hasPool: true,
    isNewConstruction: false,
    featured: true,
    propertyType: 'Condo',
    imageUrl: ASSETS.downtownSkyline,
    yearBuilt: 2018,
    lotSize: 'High-Rise Unit',
    hoaFee: '$950 / Month',
    excerpt: 'Downtown Sarasota, FL 34236 · 2 Beds · 2 Baths · 1,740 Sq Ft',
    description: 'High-floor luxury condo in downtown Sarasota bayfront corridor. Sweeping views of Sarasota Bay, Marina Jack, and the Gulf islands. Full concierge amenities, private elevator foyer, 2 assigned garage parking spaces, and heated resort pool with fitness center.',
    idxDisclaimer: 'Listing information courtesy of Stellar MLS. Information is deemed reliable but not guaranteed. IDX provided by iHomefinder Inc.'
  },
  {
    id: '5425-gulf-of-mexico-dr',
    slug: '5425-gulf-of-mexico-dr',
    title: '5425 Gulf of Mexico Dr',
    street: '5425 Gulf of Mexico Dr',
    city: 'Longboat Key',
    state: 'FL',
    zip: '34228',
    price: 3150000,
    priceFormatted: '$3,150,000',
    beds: 5,
    baths: 6,
    sqft: 5100,
    mlsNumber: 'A4592200',
    status: 'ACTIVE MLS',
    isWaterfront: true,
    hasPool: true,
    isNewConstruction: true,
    featured: true,
    propertyType: 'Single Family',
    imageUrl: ASSETS.longboatBeachfront,
    yearBuilt: 2024,
    lotSize: '0.68 Acres Direct Gulf',
    hoaFee: '$0 / No HOA',
    excerpt: 'Longboat Key, FL 34228 · 5 Beds · 6 Baths · 5,100 Sq Ft',
    description: 'Spectacular direct Gulf-front modern masterpiece on prestigious Longboat Key. Private boardwalk to private beach, infinity pool cascading toward the dunes, elevator, and smart home automation. Unrivaled sunsets every evening.',
    idxDisclaimer: 'Listing information courtesy of Stellar MLS. Information is deemed reliable but not guaranteed. IDX provided by iHomefinder Inc.'
  },
  {
    id: '280-mound-st',
    slug: '280-mound-st',
    title: '280 Mound St',
    street: '280 Mound St',
    city: 'Bird Key',
    state: 'FL',
    zip: '34236',
    price: 2890000,
    priceFormatted: '$2,890,000',
    beds: 4,
    baths: 4.5,
    sqft: 3950,
    mlsNumber: 'A4592312',
    status: 'ACTIVE MLS',
    isWaterfront: true,
    hasPool: true,
    isNewConstruction: false,
    featured: false,
    propertyType: 'Single Family',
    imageUrl: ASSETS.birdKeyEstate,
    yearBuilt: 2019,
    lotSize: 'Deepwater Canal',
    hoaFee: '$890 / Annual',
    excerpt: 'Bird Key, FL 34236 · 4 Beds · 4.5 Baths · 3,950 Sq Ft',
    description: 'Deepwater canal frontage on prestigious Bird Key with private yacht dock and 24,000 lb boat lift. Direct bay access with no fixed bridges. Chef kitchen, heated lap pool, and marble flooring.',
    idxDisclaimer: 'Listing information courtesy of Stellar MLS. Information is deemed reliable but not guaranteed. IDX provided by iHomefinder Inc.'
  },
  {
    id: '8412-prestancia-blvd',
    slug: '8412-prestancia-blvd',
    title: '8412 Prestancia Blvd',
    street: '8412 Prestancia Blvd',
    city: 'Palmer Ranch',
    state: 'FL',
    zip: '34238',
    price: 940000,
    priceFormatted: '$940,000',
    beds: 3,
    baths: 3,
    sqft: 2600,
    mlsNumber: 'A4592404',
    status: 'ACTIVE MLS',
    isWaterfront: false,
    hasPool: true,
    isNewConstruction: false,
    featured: false,
    propertyType: 'Single Family',
    imageUrl: ASSETS.palmerRanchHome,
    yearBuilt: 2016,
    lotSize: '0.28 Acres Golf Course',
    hoaFee: '$340 / Month',
    excerpt: 'Palmer Ranch, FL 34238 · 3 Beds · 3 Baths · 2,600 Sq Ft',
    description: 'Charming golf villa situated inside the guard-gated TPC Prestancia enclave of Palmer Ranch. Screened heated pool, manicured tropical grounds, and minutes from the Legacy Trail and Siesta Key Beach.',
    idxDisclaimer: 'Listing information courtesy of Stellar MLS. Information is deemed reliable but not guaranteed. IDX provided by iHomefinder Inc.'
  }
];

export const SARASOTA_ENCLAVES: Enclave[] = [
  {
    id: 'siesta-key',
    slug: 'siesta-key',
    name: 'Siesta Key',
    tag: 'Beachfront & Coastal',
    startingPrice: 'From $850,000',
    summary: 'Famous quartz sands, vibrant island village dining, tranquil canal estates, and relaxed barrier island luxury living just minutes from mainland Sarasota.',
    imageUrl: ASSETS.siestaBeach,
    features: ['#1 Beach in America', 'Vibrant Village Dining', 'Deepwater Canals', 'Barrier Island Vibe']
  },
  {
    id: 'lakewood-ranch',
    slug: 'lakewood-ranch',
    name: 'Lakewood Ranch',
    tag: 'Top Master-Planned',
    startingPrice: 'From $550,000',
    summary: 'Award-winning multi-generational community featuring premier A-rated schools, vibrant Main Street dining, polo clubs, championship golf, and over 150 miles of nature trails.',
    imageUrl: ASSETS.lakewoodGolf,
    features: ['#1 Master-Planned Community in US', 'Top A-Rated Schools', 'Polo & Tennis Clubs', '150+ Miles of Trails']
  },
  {
    id: 'downtown-sarasota',
    slug: 'downtown-sarasota',
    name: 'Downtown Sarasota',
    tag: 'Urban Bayfront & Arts',
    startingPrice: 'From $720,000',
    summary: 'Walkable marina, Marie Selby Botanical Gardens, Sarasota Opera, world-class theater district, chef-driven dining, and premier luxury high-rise condominium towers.',
    imageUrl: ASSETS.downtownSkyline,
    features: ['Marina Jack Boating', 'Selby Botanical Gardens', 'Sarasota Opera & Arts', 'Luxury High-Rise Living']
  },
  {
    id: 'longboat-key',
    slug: 'longboat-key',
    name: 'Longboat Key',
    tag: 'Exclusive Island Luxury',
    startingPrice: 'From $1,100,000',
    summary: '12 miles of private beaches, prestigious tennis and golf resorts, quiet coastal elegance, and upscale Gulf-to-bay estates.',
    imageUrl: ASSETS.longboatBeachfront,
    features: ['12 Miles of White Sand', 'The Longboat Key Club', 'Private Gated Enclaves', 'Gulf-to-Bay Estates']
  },
  {
    id: 'bird-key',
    slug: 'bird-key',
    name: 'Bird Key',
    tag: 'Private Boating & Yachting',
    startingPrice: 'From $1,800,000',
    summary: 'Gated barrier island community boasting deepwater canals, private docks, and the prestigious Bird Key Yacht Club between downtown and St. Armands Circle.',
    imageUrl: ASSETS.birdKeyEstate,
    features: ['Bird Key Yacht Club', 'Deepwater Boating / No Bridges', 'Guard Gated Security', 'Minutes to St. Armands']
  },
  {
    id: 'palmer-ranch',
    slug: 'palmer-ranch',
    name: 'Palmer Ranch',
    tag: 'Championship Golf & Nature',
    startingPrice: 'From $480,000',
    summary: 'Expansive planned community with legacy golf courses (TPC Prestancia, Stoneybrook), top-rated schools, and direct Legacy Trail access.',
    imageUrl: ASSETS.palmerRanchHome,
    features: ['TPC Prestancia 36-Hole Golf', 'Legacy Trail Biking', 'Family-Friendly Neighborhoods', 'Top Schools']
  }
];

export const AGENT_PROFILE: AgentProfile = {
  name: 'Jenna Ryan',
  title: 'Relocation & Luxury Advisor',
  role: 'Sarasota Relocation Concierge',
  bio: 'your Sarasota Relocation Concierge. I am here to help you get acquainted with the area and to possibly find the place to call home. Sarasota has a lot to offer, oceans, beaches, luxury homes, golf, parks, entertainment and fine dining. Living in Sarasota is amazing and I hope to bring you the information you need to decide if Sarasota is the place for you.',
  email: 'jennaryanflorida@gmail.com',
  phone: '(941) 555-0192',
  license: 'Florida Real Estate License #SL3492841',
  serving: 'Sarasota, Siesta Key, Lakewood Ranch & Longboat Key',
  imageUrl: ASSETS.jennaRyan,
  social: {
    linkedin: 'https://linkedin.com',
    youtube: 'https://youtube.com',
    facebook: 'https://facebook.com',
    twitter: 'https://x.com',
    instagram: 'https://instagram.com'
  }
};

export const SITE_SETTINGS: SiteSettings = {
  siteTitle: 'Finding Home in Sarasota',
  tagline: 'Your Sarasota Life is Just a Click Away',
  contactEmail: 'jennaryanflorida@gmail.com',
  activeMlsCount: 1248,
  stellarMlsFeed: 'Direct MLS Feed Updated Every 15 Minutes',
  idxProvider: 'iHomefinder Inc.',
  copyrightYear: 2025,
  disclaimer: 'Internet Data Exchange (IDX) powered by iHomefinder. All real estate information deemed reliable but not guaranteed. Equal Housing Opportunity.'
};
